events { } 
http {
    upstream servidores {
        server servidor1:5000 weight=2;
        server servidor2:5000 weight=3;
        server servidor3:5000 weight=1;
        server servidor4:5000 weight=3;
        server servidor5:5000 weight=1;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://servidores;
        }
    }
}